alias ls='lsd'
alias tree='ls --tree'

parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

setopt PROMPT_SUBST
PROMPT='%9c%{%F{green}%}$(parse_git_branch)%{%F{none}%} $ '

export TERM=xterm-256color

alias me="cd $HOME/meshcloud"
alias mf="cd $HOME/meshcloud/meshfed-release"
alias mi="cd $HOME/meshcloud/infrastructure"
alias md="cd $HOME/meshcloud/deployments"
alias mdocs="cd $HOME/meshcloud/meshcloud-docs"
alias chub="cd $HOME/meshcloud/collie-hub"
alias ccli="cd $HOME/meshcloud/collie-cli"
alias validate-dhall="mf && deployment/test/validate.sh"
alias validate-override="mf && ci/deployment/overrides-idempotent.sh"
alias format-dhall="mf && deployment/bin/format-all-osx.sh"
alias fk="fly -t k"

alias vault-forward="mi && meshstack-infra-k8s/vault-forward.sh"
export VAULT_ADDR=http://localhost:8200

alias sm='smerge'

# ssh-add -K ~/.ssh/id_rsa &> /dev/null
if [ $(ssh-add -L | grep "felix@felix-meshpad" | wc -l) -eq 0 ]; then
    ssh-add --apple-use-keychain ~/.ssh/id_rsa
fi

export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH=$HOME/.deno/bin:$PATH
export DENO_NO_UPDATE_CHECK=1

# source_collie_completions() {
#     source <(collie completions zsh) # I only enable this in collie repos since it adds a few hundred ms to shell startup time
# }
# if [[ -d '.collie' ]]; then
#     echo "It's a collie repo. collie completions enabled."
#     source_collie_completions;
# fi
# source <(unipipe completions zsh)

# GCLOUD
export USE_GKE_GCLOUD_AUTH_PLUGIN=True
# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/fzieger/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/fzieger/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
# if [ -f '/Users/fzieger/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/fzieger/google-cloud-sdk/completion.zsh.inc'; fi

